name: tests

on:
    push:
        branches:
          - master
          - '*.x'
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: true
            matrix:
                php: [7.3, 7.4, '8.0', 8.1, 8.2, 8.3, 8.4]
                laravel: [6, 7, 8, 9, 10, 11, 12]
                exclude:
                    - php: 7.3
                      laravel: 9
                    - php: 7.3
                      laravel: 10
                    - php: 7.3
                      laravel: 11
                    - php: 7.3
                      laravel: 12
                    - php: 7.4
                      laravel: 9
                    - php: 7.4
                      laravel: 10
                    - php: 7.4
                      laravel: 11
                    - php: 7.4
                      laravel: 12
                    - php: '8.0'
                      laravel: 10
                    - php: '8.0'
                      laravel: 11
                    - php: '8.0'
                      laravel: 12
                    - php: 8.1
                      laravel: 6
                    - php: 8.1
                      laravel: 7
                    - php: 8.1
                      laravel: 11
                    - php: 8.1
                      laravel: 12
                    - php: 8.2
                      laravel: 6
                    - php: 8.2
                      laravel: 7
                    - php: 8.2
                      laravel: 8
                    - php: 8.3
                      laravel: 6
                    - php: 8.3
                      laravel: 7
                    - php: 8.3
                      laravel: 8
                    - php: 8.3
                      laravel: 9
                    - php: 8.4
                      laravel: 6
                    - php: 8.4
                      laravel: 7
                    - php: 8.4
                      laravel: 8
                    - php: 8.4
                      laravel: 9
                    - php: 8.4
                      laravel: 10

        name: P${{ matrix.php }} - L${{ matrix.laravel }}

        steps:
            - name: Checkout the code
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, curl, libxml, mbstring, zip
                  ini-values: error_reporting=E_ALL
                  tools: composer:v2
                  coverage: none

            - name: Install dependencies
              run: |
                  composer update --prefer-dist --no-interaction --no-progress --with="illuminate/support:^${{ matrix.laravel }}"

            - name: Execute tests
              run: vendor/bin/phpunit --testdox --colors=always --exclude-group skipped
